name: CI/CD run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Environment Variables
        run: |
          echo "SQL_SERVER_HOST=${{ secrets.SQL_SERVER_HOST }}" >> $.env
          echo "SQL_HTTP=${{ secrets.SQL_HTTP }}" >> $.env
          echo "DATABRICKS_API_KEY=${{ secrets.DATABRICKS_API_KEY }}" >> $.env
      - name: install packages
        run: make install
      - name: install local package
        run: make setup_package
      - name: lint
        run: make lint
      - name: extract 
        run: make extract 
      - name: transform_load
        run: make transform_load 
      - name: query
        run: make query
      - name: test
        run: make test
      - name: format
        run: make format
      - name: generate_and_push
        run: make generate_and_push
      - name: deploy
        run: make deploy