name: CI/CD run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix: #strategy
        python-version: [3.8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env: 
      DATABRICKS_API_KEY: ${{ secrets.DATABRICKS_API_KEY }}
      SQL_SERVER_HOST: ${{ secrets.SQL_SERVER_HOST }}
      SQL_HTTP: ${{ secrets.SQL_HTTP }}
      JOB_ID: ${{ secrets.JOB_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: run databricks job 
        run: make job
      - name: deploy
        run: make deploy
